name: test1

on:
  push:
    branches: 
       - 'v[0-9]+.[0-9]+'
      

jobs:
  my-first-workflow:

    runs-on: ubuntu-latest

    steps:
    - name: Why echo
      run: echo "something"
    - name: echo1
      uses: actions/checkout@v3
    - name: Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Railway
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.CICDCA_RAILWAY }}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nSaw Arnt Min Zaw"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA0265084B"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\narntminzaw@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\nhttps://github.com/sawarntminzaw/Go_Fortune"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\nhttps://cheap-trousers-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://cheap-trousers-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
