name: test
on: [push]
on:
  pull_request:
    branches:
      - ['v**.**',master]   
      

jobs:
  my-first-workflow:

    runs-on: ubuntu-latest

    steps:
    - name: echo
      run: echo "something"